# Generated by Django 6.0.3 on 2026-03-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_updated', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=5000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='clientes.clients')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
