# Generated by Django 6.0.3 on 2026-03-24 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_notas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='responsavel',
            field=models.ForeignKey(default=1, help_text='Vendedor responsável por este cliente', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor/Responsável'),
        ),
    ]
